name: check-service-regions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

jobs:
  region-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Check AWS service regions
        run: |
          cd utils/aws ; ruby check_region_exclusions.rb
